version: "3"

services:

  mongo_db:
      container_name: "mongo_db"
      image: mongo:latest
      ports:
        - "27017:27017"
      networks:
        - custom
networks:
    custom:
      driver: bridge
