version: "3"

services:
  app:
    container_name: "app"
    build: .
    env_file:
        - .env
    environment:
        - MONGODB_URL=mongodb://localhost:27017/mongo_db
    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    working_dir: /source/
    volumes:
        - .:/source/
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db

  mongo_db:
      image: mongo:latest
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      networks:
        - custom
networks:
  custom:
    driver: bridge
